<?php
namespace Modules\Report\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
/**
 * Created by PhpStorm.
 * User: yue
 * Date: 2017/8/24
 * Time: 17:47
 */
class CreatePdfRequests extends FormRequest
{
    public function rules()
    {
        return[
            'date1' =>'required',
            'date2' =>'required',
        ];
    }

    public function authorize()
    {
        return true;
    }
    public function messages()
    {
        return [
            'date1.required'=>'The date field is required.',
            'date2.required'=>'The date field is required.',

        ]; // TODO: Change the autogenerated stub
    }

}